### ISSUE TITLE
About the acquisition of the data set

### ISSUE THREAD

**Issue by EXAID-Parado** [Krisloveless/ChrNet#1]
Hello, I am very interested in the data set you use in this network. I noticed that you said that the dataset will be public, but it is limited by github that cannot be uploaded, so I want to ask how can I get these datasets?

**Comment by Krisloveless** [comment]
@EXAID-Parado Hi, after several attempts, I finally got it uploaded to a public site. 
https://archive.org/download/ChrNetTrainingSet/training_tpm.tsv
https://archive.org/download/ChrNetTestingSet/testing_tpm.tsv
